Updated notes2pdf to execute source code groups

diff --git a/notes2pdf b/notes2pdf
--- a/notes2pdf
+++ b/notes2pdf
@@ -231,6 +231,85 @@ function parse_fnc
 	fi
 }
 
+# Need to fix where lang and filename or inserted
+function group_src
+{
+	local cIFS ngrps lcnt file lang
+	cIFS=$IFS
+	ngrps=`grep 'GRPS' src/groups | wc -l`
+	IFS=
+	for i in `seq 1 $ngrps`; do
+		sed -n '/GRPS/{:a;N;/GRPE/!ba;x;s/^/x/;/^x\{'"$i"'\}$/{x;p;q};x}' src/groups > src/$i.grp
+	done
+
+	for i in `seq 1 $ngrps`; do
+		lcnt=`grep 'SRCS' src/$i.grp | sort | uniq -c | wc -l`
+		if [ $lcnt -gt 1 ]; then
+			echo -e "\e[0;37m[\e[1;31m!\e[0;37m]\e[0m Mixed languages found in group #$i. Ignoring."
+		else
+			lang=`grep 'SRCS' src/$i.grp | head -1 | cut -d':' -f2`
+			file=`head -n1 src/$i.grp | cut -d':' -f2`
+			awk '/SRCS/{flag=1; next;}/SRCE/{flag=0;} flag' src/$i.grp > src/$i.src
+			cp src/$i.src src/$file
+			sed -i '1i #'"$lang"':'"$file"'' src/$i.src
+		fi
+	done
+}
+
+# Execute based on language
+function insert_src_output
+{
+	local enc
+	local sfile="$1"
+	local group=$2
+	local lang=`head -n1 $sfile | cut -d':' -f1`
+	local file=`head -n1 $sfile | cut -d':' -f2`
+	
+	case "$lang" in
+		\#python)
+			# Check for syntax errors
+			if [ $debug -eq 1 ]; then
+				python3 -m py_compile src/$file 2> >(tee debug/${file%.*}.err >&2)
+				cp src/$file debug/
+			else
+				python3 -m py_compile src/$file 2> /dev/null
+			fi
+			
+			# I pass info/error messages to stderr (1>&2) so they don't get inserted in the tex file
+			if [ $? -ne 0 ]; then
+				echo -e "\e[0;37m[\e[1;31m!\e[0;37m]\e[0m Error(s) encountered in src/$file (group #$group)" 1>&2
+			else
+				echo "\\pagebreak"
+				echo "\\begin{center}"
+				echo "\\textsc{\\large Output of code segment(s)}\\\\"
+				echo "\\end{center}"
+				echo "\\begin{minimal}"
+				if grep -q 'input(' src/$file; then
+					# How to handle capturing user input using script
+					if [ ! -f typescript ]; then
+						echo "" 1>&2
+						echo -e "\e[0;37m[\e[1;33m!\e[0;37m]\e[1;33m Action required: \e[0mRun '\e[0;37mscript -q -c \"python3 src/$file\"\e[0m'" 1>&2
+						echo -e "    Then run \e[0;37mfg\e[0m" 1>&2
+					
+						# background notes2pdf
+						(kill -SIGTSTP $$) &
+					fi
+					# cleanup the typescript file and output (formatted)
+					col -bp < typescript | tr -d '\15\32' | sed '1d;$d' | awk '/^$/ {nlstack=nlstack "\n";next;} {printf "%s",nlstack; nlstack=""; print;}' | sed -e '$ ! s/$/\\\\/g'
+			
+					rm typescript
+				else
+					python3 src/$file | tr -d '\15\32' | sed -e '$ ! s/$/\\\\/g'
+				fi
+				echo "\\end{minimal}"
+			fi
+			;;
+		# add more languages here
+		*)
+			;;
+	esac
+}
+
 # Show formatted help message
 function showhelp
 {
@@ -239,7 +318,8 @@ function showhelp
 	tr -s '\t' '\t' <<< '
 -h, --help		Display this help
 -v, --verbose	Verbose output
--d, --debug		Retain log and tex files for debugging  
+-d, --debug		Retain log and tex files for debugging
+-e, --execute	Attempt to execute source code; requires GRPS/GRPE flags present
 -o, --output <filename>	Specify the name of the PDF file
 -p, --preview	Show a preview of the PDF on completion
 ' | sed 's/\t/: :/g' | column -s ':' -t | sed 's/^/  /g'
@@ -252,6 +332,7 @@ function at_exit
 {
 	IFS=$oIFS
 	rm -rf funcs
+	rm -rf src
 	rm -f lout
 	rm -f tout
 	if [ $error -eq 0 ]; then
@@ -270,9 +351,25 @@ trap 'report_err $LINENO' ERR
 
 ##### ------ SCRIPT START ------ #####
 
+os=""
+if grep -qE "(Microsoft|WSL)" /proc/version &> /dev/null; then
+	os="win"
+elif [[ "$OSTYPE" == "darwin"* ]]; then
+	os="osx"
+else
+	os="nix"
+fi
+
+if [[ "$os" == "osx" ]]; then
+	alias sed="gsed"
+fi
+
+rm -f typescript
+
 debug=0
 output=""
 error=0
+execute=0
 preview=0
 _help=0
 verbose=0
@@ -290,6 +387,11 @@ if [ $# -gt 0 ]; then
 					;&
 				--debug)
 					debug=1
+					;;
+				-e)
+					;&
+				--execute)
+					execute=1
 					;;
 				-v)
 					;&
@@ -346,9 +448,11 @@ fi
 
 # Output message based on debug switch
 if [ $debug -eq 1 ]; then
+	rm -rf debug/
+	mkdir -p debug/
 	echo -e "\e[0;37m[\e[1;32mi\e[0;37m]\e[0m Starting notes2pdf in debug mode"
-	echo -e "   \e[0;37m[\e[1;36m+\e[0;37m]\e[0m Debug information will be stored in ${FNAME%.*}.log"
-	echo -e "   \e[0;37m[\e[1;36m+\e[0;37m]\e[0m ${FNAME%.*}.log corresponds with ${FNAME%.*}.tex"
+	echo -e "   \e[0;37m[\e[1;36m+\e[0;37m]\e[0m Debug information will be stored in debug/${FNAME%.*}.log"
+	echo -e "   \e[0;37m[\e[1;36m+\e[0;37m]\e[0m debug/${FNAME%.*}.log corresponds with debug/${FNAME%.*}.tex"
 else
 	echo -e "\e[0;37m[\e[1;32mi\e[0;37m]\e[0m Starting notes2pdf"
 fi
@@ -361,6 +465,18 @@ fi
 # output message if output file specified via output switch
 if [ ! -z $output ]; then
 	echo -e "\e[0;37m[\e[1;32mi\e[0;37m]\e[0m $FNAME will be written to $output.pdf"
+fi
+
+if [ $execute -eq 1 ]; then
+	if ! grep -q 'GRP' $FNAME; then
+		echo -e "\e[0;37m[\e[1;31m!\e[0;37m]\e[0m Source groups not defined. Ignoring execute switch"
+		execute=0
+	else
+		verbout "Execute switch set, collecting Source groups"
+		mkdir -p src/
+		awk '/GRPS/{flag=1;}/GRPE/{print; flag=0;} flag' $FNAME > src/groups
+		group_src
+	fi
 fi
 
 # out.tmp is a temporary file that contains most of the formatted content
@@ -445,15 +561,18 @@ lstc=0
 tstc=0
 equc=0
 srcc=0
+grpc=0
 
 # These are toggled to determine when inside of a block or not
 eflag=0
 sflag=0
 tflag=0
+gflag=0
 
 # The default IFS
 mIFS=
 
+# TODO Add PAGEBREAK handling immediately after GRPE
 # reads each line in the file
 while IFS=$mIFS read -r line; do
 	
@@ -463,6 +582,15 @@ while IFS=$mIFS read -r line; do
 		verbout "Start List block"
 		lstc=$((lstc+1))
 		line="_LST$lstc"
+	fi
+
+	if [[ "$line" == "GRPS"* ]]; then
+		verbout "Group start found"
+		grpc=$((grpc+1))
+	fi
+
+	if [[ "$line" == "GRPE" ]]; then
+		line="_GRP$grpc"
 	fi
 
 	if [ $tflag -eq 2 ]; then
@@ -558,10 +686,10 @@ if [ "$(ls -A funcs)" ]; then
 	done< <(ls funcs/*)
 fi
 
+IFS=
 # Format list blocks
 if grep -q 'LSTS' $FNAME; then
 	verbout "Formatting List block(s)"
-	IFS=
 	echo '' > lout
 	for i in `seq 1 $lstc`; do
 		sed -n '/LSTS/{:a;N;/LSTE/!ba;x;s/^/x/;/^x\{'"$i"'\}$/{x;p;q};x}' $FNAME > lists
@@ -609,6 +737,7 @@ echo "\end{document}" >> out.tmp
 # Final cleanup
 sed -i 's/#/\\#/g' out.tmp
 sed -i '/^LST.*/d' out.tmp
+sed -i '/^GRP.*/d' out.tmp
 sed -i '/[ \t]*\*/d' out.tmp
 
 verbout "Formatting wrapper function(s)"
@@ -616,9 +745,13 @@ verbout "Formatting wrapper function(s)"
 sed -i 's/equ(\([^]]*\))/\\( \1 \\)/g' out.tmp
 sed -i 's/uln(\([^]]*\))/\\underline{ \1 }/g' out.tmp
 
+verbout "Constructiong proper Equation blocks"
 # Format EQU* lines
 sed -i 's/EQUS/\\begin{minimal}\n\\begin{align}/g' out.tmp
 sed -i 's/EQUE/\\end{align}\n\\end{minimal}\n/g' out.tmp
+
+verbout "Adding page breaks"
+sed -i 's/PBREAK/\\pagebreak/g' out.tmp
 
 # Create the final LaTeX file by inserting formatted lists and tables where necessary
 FNAME="${FNAME%.*}"
@@ -633,6 +766,11 @@ while IFS= read -r line; do
 		verbout "Table block found. Inserting formatted content"
 		tn=$(echo $line | sed 's/_TBL//')
 		sed -n '/TBLS/{:a;N;/TBLE/!ba;x;s/^/x/;/^x\{'"$tn"'\}$/{x;p;q};x}' tout | grep -v 'TBL' >> $FNAME.tex
+	elif [[ "$line" == "_GRP"* ]]; then
+		if [ $execute -eq 1 ]; then
+			grn=$(echo $line | sed 's/_GRP//')
+			insert_src_output "src/$grn.src" $grn >> $FNAME.tex
+		fi
 	else
 		echo $line >> $FNAME.tex
 	fi
@@ -660,18 +798,12 @@ else
 	echo -e "\e[0;37m[\e[1;32mi\e[0;37m]\e[0m PDF written to $FNAME.pdf"
 fi
 
+if [ $debug -eq 1 ]; then
+	mv $FNAME.tex debug/
+	mv $FNAME.log debug/
+fi
+
 if [ $preview -eq 1 ]; then
-	verbout "Determining OS"
-	os=""
-	if grep -qE "(Microsoft|WSL)" /proc/version &> /dev/null; then
-		os="win"
-	elif [[ "$OSTYPE" == "darwin"* ]]; then
-		os="osx"
-	else
-		os="nix"
-	fi
-	verbout "OS: $os"
-	echo
 	if [ $error -eq 0 ]; then
 		echo -e "\e[0;37m[\e[1;32mi\e[0;37m]\e[0m Opening preview of $FNAME.pdf" 
 		# This is not tested
