Added documentation to notes2pdf

diff --git a/notes2pdf b/notes2pdf
--- a/notes2pdf
+++ b/notes2pdf
@@ -1,14 +1,20 @@
 #!/bin/bash
 
+# Initialize the IFS as default and store it
 IFS=
 oIFS=$IFS
 
-echo -n '' > out.tex
+# Output line number where error occurs in script
 function report_err
 {
 	echo "Error on line $1"
 }
 
+# This function parses and formats bullet lists
+# Bullet levels are denoted with indentations
+# and any text immediately following a * is treated
+# as the bullet "icon" 
+#	Ex: '*a.' in the note file becomes 'a.' in the PDF
 function list
 {
 	local file="$1"
@@ -77,6 +83,9 @@ function list
 	done
 }
 
+# This function formats TBL blocks
+# TBLS:cols:title is parsed and formatted first
+# The first column is formatted as a column title row
 function table
 {
 	local file="$1"
@@ -112,6 +121,7 @@ function table
 	done< <(awk '/TBLS/{flag=1}/TBLE/{print; flag=0}flag' $1)
 }
 
+# This function is used with equation block parsing
 function get_line_count
 {
 	local file start end num cnt
@@ -127,6 +137,7 @@ function get_line_count
 	echo $((cnt-2))
 }
 
+# Isolate frc() from within a line
 function isolate_frc
 {
 	local l="$1"
@@ -149,6 +160,7 @@ function isolate_frc
 	echo $l
 }
 
+# Parses through frc() and formats all frc() into proper LaTeX
 function parse_frc
 {
 	local l="$1"
@@ -163,6 +175,14 @@ function parse_frc
 	done | tail -n 1
 }
 
+# This function generates "function" replacement files:
+# The first argument is the input file (what needs to be parsed)
+# The second argument is the output file (where to write the replacements
+# The third argument is the function to look for
+# The fourth argument is the format string
+	# The format string follows this structure:
+	# Original text:Replacement
+# The fifth argument (optional) defines the field separator
 function parse_fnc
 {
 	local o c d
@@ -189,6 +209,8 @@ function parse_fnc
 	fi
 }
 
+# Cleanup on exit
+# Reset IFS, remove temporary files/directories
 function at_exit
 {
 	IFS=$oIFS
@@ -205,6 +227,20 @@ trap at_exit INT EXIT
 
 trap 'report_err $LINENO' ERR 
 
+# ------ SCRIPT START ------ #
+
+# Display error message and exit if file not specified or file not found
+if [ -e $1 ]; then
+	echo -e "\e[0;31mMissing notes file. Aborting\e[0m"
+	exit 1
+elif [ ! -f $1 ]; then
+	echo -e "\e[0;31mFile $1 not found. Aborting\e[0m"
+	exit 1
+fi
+
+# out.tmp is a temporary file that contains most of the formatted content
+
+# Initialize the LaTeX preamble, conditionally include based upon note contents
 cat > out.tmp <<EOF
 \\documentclass[letterpaper,12pt]{article}
 \\usepackage[letterpaper,margin=0.75in]{geometry}
@@ -260,25 +296,36 @@ cat >> out.tmp <<EOF
 EOF
 fi
 
+# Set the title format and begin the document block
 echo "\\titleformat{\\section}[block]{\\color{blue}\\Large\\bfseries\\filcenter}{}{1em}{}" >> out.tmp
 echo "\\begin{document}" >> out.tmp
 
+# funcs contains files that define replacements for certain "functions" in the note file
 mkdir -p funcs
 
+# The "function" cmb() is used for defining a choose b notation
+# parse_fnc finds all matching calls to a "function"
 parse_fnc "$1" "cmb" 'cmb(' '"cmb(%s,%s):{%s \\\\choose %s}\n",$1,$2,$1,$2' ','
 
+# these keep track of the number of each block type found in the notes file
 lstc=0
 tstc=0
 equc=0
 srcc=0
 
+# These are toggled to determine when inside of a block or not
 eflag=0
 sflag=0
 tflag=0
 
+# The default IFS
 mIFS=
+
+# reads each line in the file
 while IFS=$mIFS read -r line; do
 	
+	# These conditions are used to determine what block the current line is in
+	# And customize the line output as necessary
 	if [[ "$line" == "LSTS" ]]; then
 		lstc=$((lstc+1))
 		line="_LST$lstc"
@@ -317,22 +364,32 @@ while IFS=$mIFS read -r line; do
 	if [[ "$line" == "SRCE" ]]; then
 		sflag=0
 	fi
-
+	
+	# Format all { and } to \{ and \} if not in a source code block
 	if [ $sflag -eq 0 ]; then
 		line=$(echo $line | sed 's/{/\\{/g;s/}/\\}/g')
 	fi
 
+	# Special case: Fractions can be within fractions
 	if [[ "$line" == *"frc("* ]]; then
+		# The IFS needs to be a space now
 		IFS=" "
+		# for each "word" (field) in the line...
 		for field in $line; do
+			# if the field contains frc( 
 			if [[ "$field" == *"frc("* ]]; then
+				
+				# isolate the frc() "function"
 				iso=`isolate_frc "$field"`
+				# format the frc() "function"
 				prs=`parse_frc "$iso"`
+				# and replace it within the line
 				line=$(echo $line | sed "s~$iso~$prs~")
 			fi
 		done
 	fi
 
+	# Format the equation blocks
 	if [ $eflag -eq 1 ]; then
 		if [[ "$line" != "EQU"* ]]; then
 			line="$line \\nonumber"
@@ -342,12 +399,14 @@ while IFS=$mIFS read -r line; do
 		fi
 		cnt=$((cnt-1))
 	fi
-
+	
+	# output the line to out.tmp
 	if [ $tflag -eq 0 ] || [ $tflag -eq 2 ]; then
 		echo $line >> out.tmp
 	fi
-done < $1
+done < $1 # $1 is the input file (argument 1 on the command line)
 
+# If function replacements defined with parse_fnc, replace them
 if [ "$(ls -A funcs)" ]; then
 	while read -r fnf; do
 		while IFS=":" read -r o r; do
@@ -356,6 +415,7 @@ if [ "$(ls -A funcs)" ]; then
 	done< <(ls funcs/*)
 fi
 
+# Format list blocks
 IFS=
 echo '' > lout
 for i in `seq 1 $lstc`; do
@@ -366,6 +426,7 @@ for i in `seq 1 $lstc`; do
 	rm lists
 done
 
+# Format table blocks
 echo '' > tout
 for i in `seq 1 $tstc`; do
 	sed -n '/TBLS/{:a;N;/TBLE/!ba;x;s/^/x/;/^x\{'"$i"'\}$/{x;p;q};x}' $1 > tables
@@ -375,6 +436,7 @@ for i in `seq 1 $tstc`; do
 	rm tables
 done
 
+# Replace SRC* lines with proper LaTeX/listings beginning/end
 while read -r line; do
 	lang=`cut -d':' -f2 <<< $line`
 	sed -i "s~$line~\\\\begin{minimal}\n\\\\begin{lstlisting}[language=$lang]~" out.tmp
@@ -382,6 +444,7 @@ done< <(grep 'SRCS' out.tmp)
 
 sed -i "s/^SRCE/\\\\end{lstlisting}\n\\\\end{minimal}/g" out.tmp
 
+# Replace '# Title' lines with proper LaTeX headers
 while read -r line; do
 	title=`cut -d' ' -f 2- <<< $line`
 
@@ -389,17 +452,25 @@ while read -r line; do
 	sed -i "s~$line~$title~" out.tmp
 done< <(grep '^# ' out.tmp)
 
+# End the document block
 echo "\end{document}" >> out.tmp
+
+# Final cleanup
 sed -i 's/#/\\#/g' out.tmp
 sed -i '/^LST.*/d' out.tmp
 sed -i '/[ \t]*\*/d' out.tmp
+
+# Replace wrapper functions with their LaTeX equivalent
 sed -i 's/equ(\([^]]*\))/\\( \1 \\)/g' out.tmp
 sed -i 's/uln(\([^]]*\))/\\underline{ \1 }/g' out.tmp
 
+# Format EQU* lines
 sed -i 's/EQUS/\\begin{minimal}\n\\begin{align}/g' out.tmp
 sed -i 's/EQUE/\\end{align}\n\\end{minimal}\n/g' out.tmp
 
+# Get the file name from $1
 fname="${1%.*}"
+# Create the final LaTeX file by inserting formatted lists and tables where necessary
 while IFS= read -r line; do
 
 	if [[ "$line" == "_LST"* ]]; then
@@ -413,6 +484,7 @@ while IFS= read -r line; do
 	fi
 done < out.tmp
 
+# Generate the PDF and display success/error messages
 pdflatex -interaction=nonstopmode $fname.tex
 stat=$?
 if [ $stat -ne 0 ]; then
